// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf7TKAi2N18Oz3fbc-HGiGDXgvGkf6rkk',
    appId: '1:779084083568:web:65721c0266c38ea8731fb5',
    messagingSenderId: '779084083568',
    projectId: 'signup-f123a',
    authDomain: 'signup-f123a.firebaseapp.com',
    storageBucket: 'signup-f123a.appspot.com',
    measurementId: 'G-4VHJ03505Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlxnI0XYzbfaZVyDqgfoAM8DU6Q4thW3o',
    appId: '1:779084083568:android:601a64e2547961df731fb5',
    messagingSenderId: '779084083568',
    projectId: 'signup-f123a',
    storageBucket: 'signup-f123a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAASz9YZDFcm_5Q3jFVRgZjxihjjlqzuuY',
    appId: '1:779084083568:ios:76ddcbb6a550303f731fb5',
    messagingSenderId: '779084083568',
    projectId: 'signup-f123a',
    storageBucket: 'signup-f123a.appspot.com',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAASz9YZDFcm_5Q3jFVRgZjxihjjlqzuuY',
    appId: '1:779084083568:ios:76ddcbb6a550303f731fb5',
    messagingSenderId: '779084083568',
    projectId: 'signup-f123a',
    storageBucket: 'signup-f123a.appspot.com',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf7TKAi2N18Oz3fbc-HGiGDXgvGkf6rkk',
    appId: '1:779084083568:web:3833f237c2a6bbca731fb5',
    messagingSenderId: '779084083568',
    projectId: 'signup-f123a',
    authDomain: 'signup-f123a.firebaseapp.com',
    storageBucket: 'signup-f123a.appspot.com',
    measurementId: 'G-VD30EC1MLN',
  );
}
